services:
  testdocling:
    image: ${DOCKER_REGISTRY-}testdocling
    build:
      context: .
      dockerfile: TestDocling/Dockerfile
    ports:
    - "5000:80"
    depends_on:
    - docling
    environment:
    - DOCLING_URL=http://docling:5001

  docling:
    image: quay.io/docling-project/docling-serve
    ports:
    - "5001:5001"
 
