services:
  testdocling:
    image: ${DOCKER_REGISTRY-}testdocling
    build:
      context: .
      dockerfile: TestDocling/Dockerfile
    ports:
    - "5000:80"
    environment:
    - DOCLING_URL=http://10.0.0.135:5001
    - OLLAMA_URL=http://host.docker.internal:11434


    
    